 CREATE TABLE [USER](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 Email VARCHAR(50) NOT NULL,
 [Password] VARCHAR(200) NOT NULL,
 IsActive BIT NOT NULL,
 DtUpdate DATETIME NOT NULL
 );
 
 CREATE TABLE [FOLDER](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 DtCreate DATETIME NOT NULL,
 DtUpdate DATETIME NOT NULL,
 IdUser INT NOT NULL,
 IdParentFolder INT NOT NULL,
 FOREIGN KEY (IdUser) REFERENCES [USER](Id)
 );
 
 CREATE TABLE [TYPE](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 Extension VARCHAR(10) NOT NULL,
 ImagePath VARCHAR(200) NOT NULL,
 DtUpdate DATETIME NOT NULL
 );
 
 CREATE TABLE [FILE](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 [Path] VARCHAR(200) NOT NULL,
 DtUpdate DATETIME NOT NULL,
 IdFolder INT NOT NULL,
 IdType INT NOT NULL,
 FOREIGN KEY (IdType) REFERENCES [TYPE](Id),
 FOREIGN KEY (IdFolder) REFERENCES FOLDER(Id)
 );