 CREATE TABLE [User](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 Email VARCHAR(50) NOT NULL,
 [Password] VARCHAR(200) NOT NULL,
 IsActive BIT NOT NULL,
 ResetPasswordHash VARCHAR(200) NULL,
 IsResetPasswordActive BIT NULL,
 ResetPasswordCode VARCHAR(50) NULL,
 DtUpdate DATETIME NOT NULL
 );
 
 CREATE TABLE [Folder](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 DtCreate DATETIME NOT NULL,
 DtUpdate DATETIME NOT NULL,
 IdUser INT NOT NULL,
 IdParentFolder INT NOT NULL,
 FOREIGN KEY (IdUser) REFERENCES [USER](Id)
 );
 
 CREATE TABLE [Type](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 Extension VARCHAR(10) NOT NULL,
 ImagePath VARCHAR(200) NOT NULL,
 DtUpdate DATETIME NOT NULL
 );
 
 CREATE TABLE [File](
 Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 [Path] VARCHAR(200) NOT NULL,
 DtUpdate DATETIME NOT NULL,
 IdFolder INT NOT NULL,
 IdType INT NOT NULL,
 FOREIGN KEY (IdType) REFERENCES [TYPE](Id),
 FOREIGN KEY (IdFolder) REFERENCES FOLDER(Id)
 );